import { FilterImpl } from 'liquidjs/dist/template/filter/filter-impl';
import { ImportFrom, RegistrationSymbol } from '../../generator/generatorContext';
import { getRelativePath } from '../utils';

export function toImportFilter(this: FilterImpl, importFrom: ImportFrom, outputDir: string): string {
  const importPath = getRelativePath(outputDir, importFrom);
  switch (importFrom.kind) {
    case 'Default': {
      return `import ${importFrom.name} from '${importPath}';`
    }
    case 'Named': {
      if (importFrom.alias === importFrom.name) {
        return `import { ${importFrom.name} } from '${importPath}';`
      }

      return `import { ${importFrom.name} as ${importFrom.alias} } from '${importPath}';`
    }
    case 'Namespace': {
      return `import * as ${importFrom.alias} from '${importPath}';`
    }
  }

  throw Error(`The import-kind is not supported`);
}

export function toSymbolPath(this: FilterImpl, symbolDescriptor: RegistrationSymbol): string {
  const symbolPath: string[] = [];
  if (symbolDescriptor.autoGenerated) {
    symbolPath.push('__SERVICE_TYPE_SYMBOLS')
  }

  if (symbolDescriptor.symbolNamespace.length !== 0) {
    symbolPath.push(symbolDescriptor.symbolNamespace);
  }

  symbolPath.push(symbolDescriptor.symbolId);
  return symbolPath.join('.');
}